name = "bench-chat"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-01-12"
compatibility_flags = ["streams_enable_constructors"]
account_id = "90101201ef6f6f2b460284210d2037db"

services = [
  { binding = "EMITTER", service = "emitter-service" }
]

[env.production]
routes = [
	{ pattern = "chat.bench.codes", custom_domain = true, zone_name = "bench.codes" }
]

[site]
  bucket = "./public"

[build.production]
  command = "npm run build"
